---

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Create sites folders
  file: path=/etc/nginx/sites-available state=directory mode=0755
  with_items:
    - /etc/nginx/sites-enabled

- name: Create nginx global config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy vascan config
  copy: src=vascan.ru.conf dest=/etc/nginx/sites-available/vascan.ru.conf

- name: Create symlink to vascan config
  file: src=/etc/nginx/sites-available/vascan.ru.conf dest=/etc/nginx/sites-enabled/vascan.ru.conf state=link
  notify: restart nginx
